#!/bin/bash
##Written by Brian Winkler
##Liscensed under the GPL
##Check out my blog at https://nuxview.blogspot.com/
##COntact me at <brianewinkler@gmail.com>


##Run sshuttle

##Replace [user@host] with your ssh login credentials
##The & forks the process to the background
##Delete the & if you dont have ssh set-up to automatically login to your server
Freedom=$(sshuttle -D -r [user@host] 0/0) &

##Execute command
echo "$Freedom"
